# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxswiftcourse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'rxswiftcourseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxswiftcourseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
